### ISSUE TITLE
Not compatible with Docker v1.11.x

### ISSUE THREAD

**Issue by krancour** [deis/registry#60]
I've been using the `kube-aws` tool from [coreos/coreos-kubernetes](https://github.com/coreos/coreos-kubernetes) to stand up my dev / test clusters in AWS. By default, the CoreOS nodes that get created use the latest image from CoreOS' _alpha_ release channel. As of July 2, the latest release in that channel (1097.0.0) is the first CoreOS release to include Docker >= v1.11.0 (specifically, v1.11.2).

Since then, all pushes to Deis' internal registry fail. The logs below were captured from the controller and demonstrate a timeout is occurring. The controller, however, can probably be exonerated, as even a direct, manual `docker push` to the registry from any worker nodes fails. `telnet <registry svc ip> 80` succeeds, so there would not seem to be any issue of connectivity at play.

Reverting to Docker 1.10.3 by building a new cluster using the _beta_ channel (release 1068.3.0) does indeed correct the issue. A quick scan of Docker v1.11.x release notes does not reveal anything obvious that would explain this.

```
INFO [megaboom]: kent created initial release
INFO [megaboom]: domain megaboom added
10.2.52.0 "POST /v2/apps/ HTTP/1.1" 201 159 "Deis Client v2.2.0-dev"
INFO [megaboom]: build megaboom-6c52897 created
INFO [megaboom]: kent deployed quay.io/arschles/megaboom:devel
INFO Pulling Docker image quay.io/arschles/megaboom:devel
INFO Tagging Docker image quay.io/arschles/megaboom:devel as 10.3.0.128:80/megaboom:v2
INFO Pushing Docker image 10.3.0.128:80/megaboom:v2
ERROR:root:Uncaught Exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/requests/packages/urllib3/response.py", line 228, in _error_catcher
    yield
  File "/usr/local/lib/python3.5/dist-packages/requests/packages/urllib3/response.py", line 310, in read
    data = self._fp.read(amt)
  File "/usr/lib/python3.5/http/client.py", line 448, in read
    n = self.readinto(b)
  File "/usr/lib/python3.5/http/client.py", line 478, in readinto
    return self._readinto_chunked(b)
  File "/usr/lib/python3.5/http/client.py", line 573, in _readinto_chunked
    chunk_left = self._get_chunk_left()
  File "/usr/lib/python3.5/http/client.py", line 541, in _get_chunk_left
    chunk_left = self._read_next_chunk_size()
  File "/usr/lib/python3.5/http/client.py", line 501, in _read_next_chunk_size
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "/app/api/views.py", line 171, in create
    return super(AppResourceViewSet, self).create(request, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/mixins.py", line 21, in create
    self.perform_create(serializer)
  File "/app/api/viewsets.py", line 21, in perform_create
    self.post_save(obj)
  File "/app/api/views.py", line 246, in post_save
    self.release = build.create(self.request.user)
  File "/app/api/models/build.py", line 60, in create
    source_version=self.version
  File "/app/api/models/release.py", line 88, in new
    release.publish()
  File "/app/api/models/release.py", line 135, in publish
    publish_release(source_image, self.image, deis_registry, self.get_registry_auth())
  File "/app/registry/dockerclient.py", line 197, in publish_release
    return DockerClient().publish_release(source, target, deis_registry, creds)
  File "/app/registry/dockerclient.py", line 116, in publish_release
    self.push("{}/{}".format(self.registry, name), tag)
  File "/app/registry/dockerclient.py", line 138, in push
    log_output(stream, 'push', repo, tag)
  File "/app/registry/dockerclient.py", line 176, in log_output
    for chunk in stream:
  File "/usr/local/lib/python3.5/dist-packages/docker/client.py", line 225, in _stream_helper
    data = reader.read(1)
  File "/usr/local/lib/python3.5/dist-packages/requests/packages/urllib3/response.py", line 320, in read
    flush_decoder = True
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.5/dist-packages/requests/packages/urllib3/response.py", line 233, in _error_catcher
    raise ReadTimeoutError(self._pool, None, 'Read timed out.')
requests.packages.urllib3.exceptions.ReadTimeoutError: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out.
10.2.52.0 "POST /v2/apps/megaboom/builds/ HTTP/1.1" 500 25 "Deis Client v2.2.0-dev"
```

**Comment by kmala** [comment]
are you regularly able to reproduce it as this looks like aws issue(overloading the machine) https://github.com/docker/docker-py/issues/398.there are many issues in the docker repo similar to this even in the earlier versions of it.

**Comment by krancour** [comment]
Yes. I can reliably reproduce this on AWS, but only when using Docker v1.11. Using Docker v1.10, everything is reliably working on AWS. If you like I can give you access to two such clusters for comparison.

**Comment by krancour** [comment]
@kmala what is the reason we're using our own fork of docker/distribution?

**Comment by kmala** [comment]
initially it was to support minio and have the feature of creating the buckets/containers if they don't exist.Later i merged few changes upstream and have one more open PR(https://github.com/docker/distribution/pull/1783)  once merged we can move away from our own fork.

**Comment by krancour** [comment]
Although rolling back to Docker v1.10 solves the problem, I cannot seem to fix this by instead keeping v1.11 and updating to the latest code from docker/distribution. I would have expected that to work. Note that the buckets in question already exist, so I'm not being bitten by the lack of just-in-time bucket creation or anything like that. The symptoms remain identical to what I reported in my OP.

**Comment by krancour** [comment]
It turns out the failure looks a little different if the controller and registry turn out to be co-located on the same node. (Constant retries to push instead of a failure to dial.) I wonder if this might point to some incompatibility between Docker v1.11 and the kube-proxy.

**Comment by krancour** [comment]
On the off chance it would have helped, I upgraded my cluster to k8s 1.3.0 and the problem persists.

**Comment by krancour** [comment]
Ok... seems k8s 1.2 and 1.3 aren't certified as Docker v1.11 compatible yet. It's a WIP:

https://github.com/kubernetes/kubernetes/issues/23397

I'm not going to close this issue, but I think we can sit on it at least until k8s is known to work with Docker 1.11-- otherwise we're really putting the cart before the horse.

**Comment by arschles** [comment]
@krancour since we're sitting on this issue, can we move this out of the 2.2 milestone?

**Comment by krancour** [comment]
@arschles, yes.

**Comment by mboersma** [comment]
>  until k8s is known to work with Docker 1.11

That is the case now, and compatibility with Docker in general is unfortunately something we have to rely on k8s to ensure.
